clear all; close all; clc;
% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 05-Dec-2018 14:04:04
%
% This script assumes these variables are defined:
%
%   irisInputs - input data.

load('iris_dataset.mat');

x = irisInputs;

% Create a Self-Organizing Map
dimension1 = 3;
dimension2 = 3;
net = selforgmap([dimension1 dimension2],10,3,'gridtop','dist');

% Choose Plot Functions
% For a list of all plot functions type: help nnplot
net.plotFcns = {'plotsomtop','plotsomnc','plotsomnd', ...
    'plotsomplanes', 'plotsomhits', 'plotsompos'};

% Train the Network
[net,tr] = train(net,x);

% Test the Network
y = net(x);

% View the Network
%view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

% Deployment
% Change the (false) values to (true) to enable the following code blocks.
% See the help for each generation function for more information.
if (false)
    % Generate MATLAB function for neural network for application
    % deployment in MATLAB scripts or with MATLAB Compiler and Builder
    % tools, or simply to examine the calculations your trained neural
    % network performs.
    genFunction(net,'myNeuralNetworkFunction');
    y = myNeuralNetworkFunction(x);
end
if (false)
    % Generate a matrix-only MATLAB function for neural network code
    % generation with MATLAB Coder tools.
    genFunction(net,'myNeuralNetworkFunction','MatrixOnly','yes');
    y = myNeuralNetworkFunction(x);
end
if (false)
    % Generate a Simulink diagram for simulation or deployment with.
    % Simulink Coder tools.
    gensim(net);
end

%%
%hasta aqui te lo genera solo

%change the fromta of the outputs so that siloute function is able 
%to read it
N=dimension1*dimension2;% clusters
C_2=zeros(1,N);
for k=1:150
    aux = y(:,k);
    for j= 1:N
       if aux(j)==1
           C_2(k)=j;
       end
    end
end

silhouette(irisInputs',C_2);